[data]
root = "data"
log = "data/logs"
db = "data/screening.db"
irbank = "data/irbank"
export_csv = "data/all_stocks.csv"
proxy_failure_cache = "data/.proxy_failures.json"
not_a_proxy_list = "data/not_a_proxy.txt"
